import json
import os
import matplotlib.pyplot as plt

class ScoreTimeline:
    """Generates visualizations for debate transcripts."""

    def generate(self, transcript_path: str) -> dict:
        """Reads transcript JSON and generates charts in assets/."""
        if not os.path.exists("assets"):
            os.makedirs("assets")

        with open(transcript_path, "r") as f:
            data = json.load(f)

        rounds = data.get("rounds", [])
        if not rounds:
            return {"status": "error", "message": "No rounds found in transcript."}

        round_numbers = []
        pro_tokens = []
        con_tokens = []
        pro_scores = []
        con_scores = []
        
        for idx, r in enumerate(rounds):
            round_numbers.append(r["round_number"])
            
            # Estimate tokens as words * 1.3
            p_toks = int(len(r.get("pro_message", "").split()) * 1.3)
            c_toks = int(len(r.get("con_message", "").split()) * 1.3)
            pro_tokens.append(p_toks)
            con_tokens.append(c_toks)
            
            # Use real scores generated by the MasterAgent, normalized to sum to 100
            p_score = r.get("pro_score", 50.0)
            c_score = r.get("con_score", 50.0)
            tot = p_score + c_score
            if tot > 0:
                p_score = (p_score / tot) * 100
                c_score = (c_score / tot) * 100
            pro_scores.append(p_score)
            con_scores.append(c_score)

        # Configure matplotlib style
        try:
            plt.style.use('seaborn-v0_8-darkgrid')
        except OSError:
            pass  # Fallback to default if style not found

        topic = data.get('topic', 'Debate')
        verdict = data.get("verdict", {})
        v_pro_score = verdict.get("pro_score", 50)
        v_con_score = verdict.get("con_score", 50)
        v_tot = v_pro_score + v_con_score
        if v_tot > 0:
            v_pro_score = (v_pro_score / v_tot) * 100
            v_con_score = (v_con_score / v_tot) * 100
        v_winner = verdict.get("winner", "tie").upper()

        # 1. Plot Score Timeline
        plt.figure(figsize=(10, 6), dpi=150)
        plt.plot(round_numbers, pro_scores, marker='o', label='Hitchens (Pro)', color='#b22222', linewidth=2.5, markersize=8)
        plt.plot(round_numbers, con_scores, marker='o', label='Chomsky (Con)', color='#2c5282', linewidth=2.5, markersize=8)
        
        # Add horizontal dashed lines for final scores
        if v_pro_score:
            plt.axhline(y=v_pro_score, color='#b22222', linestyle=':', alpha=0.6)
        if v_con_score:
            plt.axhline(y=v_con_score, color='#2c5282', linestyle=':', alpha=0.6)

        # Add winner text box
        winner_name = "Hitchens" if v_winner == "PRO" else "Chomsky" if v_winner == "CON" else "Tie"
        textstr = f"FINAL VERDICT\nHitchens: {v_pro_score:.1f} | Chomsky: {v_con_score:.1f}\nWINNER: {winner_name} *"
        props = dict(boxstyle='round', facecolor='white', alpha=0.9, edgecolor='gray')
        plt.gca().text(0.02, 0.96, textstr, transform=plt.gca().transAxes, fontsize=10,
                       verticalalignment='top', bbox=props, fontweight='bold')

        plt.title("Debate Persuasion Score Timeline", fontsize=16, fontweight='bold', pad=20)
        plt.suptitle(f"Topic: {topic}", fontsize=12, y=0.92, fontstyle='italic')
        plt.xlabel("Round Number", fontsize=12)
        plt.ylabel("Persuasion Score (0-100)", fontsize=12)
        plt.legend(loc="lower right", fontsize=10)
        plt.grid(True, linestyle='--', alpha=0.7)
        plt.tight_layout(rect=[0, 0, 1, 0.95])
        plt.savefig("assets/score_timeline.png", dpi=150, bbox_inches="tight")
        plt.close()

        # 2. Plot Token Usage (Stacked Bar)
        plt.figure(figsize=(10, 6), dpi=150)
        x = [r for r in round_numbers]
        plt.bar(x, pro_tokens, label='Hitchens Tokens', color='#b22222', alpha=0.8)
        plt.bar(x, con_tokens, bottom=pro_tokens, label='Chomsky Tokens', color='#2c5282', alpha=0.8)
        plt.title("Token Usage per Round", fontsize=16, fontweight='bold', pad=20)
        plt.suptitle(f"Topic: {topic}", fontsize=12, y=0.92, fontstyle='italic')
        plt.xlabel("Round Number", fontsize=12)
        plt.ylabel("Estimated Tokens Used", fontsize=12)
        plt.xticks(x)
        plt.legend(loc="best", fontsize=11)
        plt.grid(axis='y', linestyle='--', alpha=0.7)
        plt.tight_layout(rect=[0, 0, 1, 0.95])
        plt.savefig("assets/token_usage.png", dpi=150, bbox_inches="tight")
        plt.close()

        # 3. Plot Final Verdict Bar Chart
        plt.figure(figsize=(10, 4), dpi=150)
        agents = ['Chomsky (Con)', 'Hitchens (Pro)']  # Reverse order so Pro is on top typically
        scores = [v_con_score, v_pro_score]
        
        # Highlight winner
        colors = ['#2c5282', '#b22222']
        if v_winner == "PRO":
            colors = ['#7a96b3', '#b22222']  # Dim Chomsky
        elif v_winner == "CON":
            colors = ['#2c5282', '#d17b7b']  # Dim Hitchens

        bars = plt.barh(agents, scores, color=colors, alpha=0.9)
        plt.title("Final Verdict Score Comparison", fontsize=16, fontweight='bold', pad=15)
        plt.suptitle(f"Topic: {topic}", fontsize=12, y=0.95, fontstyle='italic')
        plt.xlabel("Total Persuasion Score (0-100)", fontsize=12)
        
        # Add text labels on bars
        for bar in bars:
            width = bar.get_width()
            plt.text(width - 2, bar.get_y() + bar.get_height()/2, f"{width:.1f}", 
                     ha='right', va='center', color='white', fontweight='bold', fontsize=12)
                     
        plt.xlim(0, max(max(scores) * 1.1, 100))
        plt.grid(axis='x', linestyle='--', alpha=0.7)
        plt.tight_layout(rect=[0, 0, 1, 0.90])
        plt.savefig("assets/final_verdict.png", dpi=150, bbox_inches="tight")
        plt.close()

        return {
            "score_timeline": "assets/score_timeline.png",
            "token_usage": "assets/token_usage.png",
            "final_verdict": "assets/final_verdict.png"
        }
