import json
import os
import random
import matplotlib.pyplot as plt

class ScoreTimeline:
    """Generates visualizations for debate transcripts."""

    def generate(self, transcript_path: str) -> dict:
        """Reads transcript JSON and generates charts in assets/."""
        if not os.path.exists("assets"):
            os.makedirs("assets")

        with open(transcript_path, "r") as f:
            data = json.load(f)

        rounds = data.get("rounds", [])
        if not rounds:
            return {"status": "error", "message": "No rounds found in transcript."}

        round_numbers = []
        pro_tokens = []
        con_tokens = []
        pro_scores = []
        con_scores = []
        
        for idx, r in enumerate(rounds):
            round_numbers.append(r["round_number"])
            
            # Estimate tokens as words * 1.3
            p_toks = int(len(r.get("pro_message", "").split()) * 1.3)
            c_toks = int(len(r.get("con_message", "").split()) * 1.3)
            pro_tokens.append(p_toks)
            con_tokens.append(c_toks)
            
            # Use real scores generated by the MasterAgent
            pro_scores.append(r.get("pro_score", 50.0))
            con_scores.append(r.get("con_score", 50.0))

        # 1. Plot Score Timeline
        plt.figure(figsize=(10, 6))
        plt.plot(round_numbers, pro_scores, marker='o', label='Pro Score', color='#1f77b4', linewidth=2)
        plt.plot(round_numbers, con_scores, marker='o', label='Con Score', color='#d62728', linewidth=2)
        plt.title(f"Score Timeline: {data.get('topic', 'Debate')}")
        plt.xlabel("Round Number")
        plt.ylabel("Persuasion Score")
        plt.legend()
        plt.grid(True, linestyle='--', alpha=0.7)
        plt.tight_layout()
        plt.savefig("assets/score_timeline.png", dpi=150)
        plt.close()

        # 2. Plot Token Usage
        plt.figure(figsize=(10, 6))
        bar_width = 0.35
        x = [r for r in round_numbers]
        plt.bar([pos - bar_width/2 for pos in x], pro_tokens, width=bar_width, label='Pro Tokens', color='#1f77b4', alpha=0.8)
        plt.bar([pos + bar_width/2 for pos in x], con_tokens, width=bar_width, label='Con Tokens', color='#d62728', alpha=0.8)
        plt.title(f"Token Usage per Round: {data.get('topic', 'Debate')}")
        plt.xlabel("Round Number")
        plt.ylabel("Estimated Tokens")
        plt.xticks(x)
        plt.legend()
        plt.grid(axis='y', linestyle='--', alpha=0.7)
        plt.tight_layout()
        plt.savefig("assets/token_usage.png", dpi=150)
        plt.close()

        return {
            "score_timeline": "assets/score_timeline.png",
            "token_usage": "assets/token_usage.png"
        }
